### ISSUE TITLE
改了一下 release 版，从表面上适配了 Taro 3

### ISSUE THREAD

**Issue by slobber** [Miaonster/taro-code#18]
https://www.npmjs.com/package/taro3-code

有需要的可以使用..........

**Comment by chasekafei** [comment]
哈哈哈怎么叫从表面上适配？项目迁移 Taro3 也遇到这个问题了，求教下是修改了什么内容？

> https://www.npmjs.com/package/taro3-code
> 
> 有需要的可以使用..........

**Comment by slobber** [comment]
> 哈哈哈怎么叫从表面上适配？项目迁移 Taro3 也遇到这个问题了，求教下是修改了什么内容？
> 
> > https://www.npmjs.com/package/taro3-code
> > 有需要的可以使用..........

就是让 release 版能在 Taro3 上使用，具体的忘了，你可以 diff 一下........

**Comment by Miaonster** [comment]
已经支持 taro 3，安装最新版即可
