### ISSUE TITLE
无法编译成功，h5，微信都不行

### ISSUE THREAD

**Issue by xahy123** [Miaonster/taro-code#25]
![1](https://user-images.githubusercontent.com/43662455/99255485-f6511080-284e-11eb-8fe6-8f557897f2a6.png)

**Comment by Miaonster** [comment]
taro-code 支持 taro 3.0 版本，如果在使用 taro 2.0，可以看一下 2.x 的文档 https://github.com/Miaonster/taro-code/tree/taro-2.x
