### ISSUE TITLE
运行出错

### ISSUE THREAD

**Issue by Winwuwentao** [Miaonster/taro-code#28]
需要在taro 文件中配置usingComponents吗？
![DBCC51D2-BE8D-47B3-B015-59E448756F3F](https://user-images.githubusercontent.com/23164538/110559571-6b8a7d80-817f-11eb-9531-50cfc60d6d58.png)

**Comment by Miaonster** [comment]
参考 https://github.com/Miaonster/taro-code/tree/master/packages/taro-code-demo
如果使用 taro2.0，可以查看2.0的文档 https://github.com/Miaonster/taro-code/tree/taro-2.x
