### ISSUE TITLE
编译报错  ‘node_modules/css-loader/dist/runtime/url-escape.js’ 不存在

### ISSUE THREAD

**Issue by Hallelujah828** [Miaonster/taro-code#41]
taro版本2.2.1

操作：yarn add taro-code@2

报错：
./node_modules/@tarojs/webpack-runner/node_modules/css-loader/dist/runtime/url-escape.js
Module build failed (from ./node_modules/@tarojs/webpack-runner/node_modules/babel-loader/lib/index.js):
Error: ENOENT: no such file or directory, open '/Users/li/Desktop/work-zhou/wanling-web-mobile/node_modules/@tarojs/webpack-runner/node_modules/css-loader/dist/runtime/url-escape.js'

**Comment by Miaonster** [comment]
2.x 不维护了，考虑一下升级
